### ISSUE TITLE
rows/backs limit

### ISSUE THREAD

**Issue by GothkittyGirl** [Eufranio/SpongyBackpacks#1]
how do i allow more then 2 backs/rows?

**Comment by Eufranio** [comment]
Assign the Option (meta) value of `spongybackpacks.limit.rows` or `spongybackpacks.limit.backpacks` to the number of rows/backpacks a subject can have, on your permissions plugin. On luckperms you'd use `/lp group default meta set spongybackpacks.limit.rows 5`  to set the limit of rows to the **default** group to **5**.

**Comment by GothkittyGirl** [comment]
thank you very much that works :)
