### ISSUE TITLE
LuckPerms Permission Problems

### ISSUE THREAD

**Issue by SeanStoves** [Eufranio/SpongyBackpacks#2]
We use a few of your mods, and we have the constant problem that they don't seem to acknowledge / recognize context based permissions.      We have alot of ranks where we prefer to be server=dw20, server=beyond, server=sf3.

However, it seems SpongyBackpacks and MagiBridge don't check the contexts..  Is this something that can be fixed?

**Comment by Eufranio** [comment]
They should be checking the contexts. I use `Subject#hasPermission` and `Subject#getOption`, which are supposed to calculate the context of the player when invoked. @lucko any clue?

**Comment by lucko** [comment]
Looks fine to me.

@SolaoBajiuik You can check with the verbose command to see which contexts are being used for each permission check.

https://github.com/lucko/LuckPerms/wiki/Verbose

It's most likely an issue with the way your permissions are configured.

**Comment by Eufranio** [comment]
Thanks for clarifying this!
