### ISSUE TITLE
Error occurred while executing command:...

### ISSUE THREAD

**Issue by darkire1997** [Eufranio/SpongyBackpacks#5]
So I installed SpongyBackpacks on my Pixelmon server and I got the following message when creating a backpack with the command /sb create Ores 2 darkire1997 and I got the following message:
**Error occurred while executing command: Configuration does not accept objects of type class io.github.eufranio.spongybackpacks..data.BackpackData**
My server mod folder has the following mods and plugins:

1. AnotherGymPlugin-1.12.2-0.5.5-beta.jar
2. ChunkAnimator-MC1.12-1.2.jar
3. Custom-Main-Menu-Mod-1.12.2.jar
4. CustomNPCs_1.12.219apr18snapshot.jar
5. holograms-3.1.5.jar
6. LuckPerms-Sponge-4.2.42.jar
7. Nucleus-1.4.4-S7.0-MC1.12.2-plugin.jar
8. OptiFine_1.12.2_HD_U_D3.jar
9. PixelExtras-1.12.2-2.3.8-universal.jar
10. PixelGenocide-1.0.3.jar
11. Pixelmon-1.12.2-6.3.1-universal.jar
12. projectcore-7.0.0-0.2.1.jar
13. RedProtect-7.3.0-b68-Universal.jar
14. ResourceLoader-MC1.12.1-1.5.3.jar
15. SkinChanger.jar
16. spongeforge-1.12.2-2705-7.1.0-BETA-3262.jar
17. SpongyBackpacks-1.0.jar
18. VariedCommodities_1.12.2(06nov17).jar

And my server type is Forge 14.23.4.2708 (1.12.2) @ Java 8.

**Comment by Eufranio** [comment]
The latest recommended build of Sponge should fix those issues. Update if you haven't already.
